# Generated by Django 4.2.7 on 2025-08-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='recipient',
            field=models.CharField(default='tangentohost@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sender',
            field=models.CharField(default='abuse@contabo.com', max_length=255),
        ),
    ]
