# Generated by Django 4.2.7 on 2025-08-12 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abuse_monitor', '0002_ticket_recipient_ticket_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='received_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_register', 'User Registration'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('ticket_view', 'Ticket Viewed'), ('ticket_create', 'Ticket Created'), ('ticket_update', 'Ticket Updated'), ('ticket_status_change', 'Ticket Status Changed'), ('ticket_priority_change', 'Ticket Priority Changed'), ('ticket_delete', 'Ticket Deleted'), ('email_monitor_start', 'Email Monitoring Started'), ('email_monitor_stop', 'Email Monitoring Stopped'), ('email_received', 'Email Received'), ('ai_analysis', 'AI Analysis Performed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('chat_message', 'Chat Message Sent'), ('chat_analysis', 'Chat Analysis Requested'), ('chat_reset', 'Chat Reset'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('system_config', 'System Configuration Changed'), ('error_occurred', 'Error Occurred'), ('api_failure', 'API Failure'), ('connection_failed', 'Connection Failed')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse_monitor.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'created_at'], name='abuse_monit_user_id_75ed4d_idx'), models.Index(fields=['activity_type', 'severity', 'created_at'], name='abuse_monit_activit_4b611a_idx'), models.Index(fields=['related_ticket', 'created_at'], name='abuse_monit_related_8008f2_idx')],
            },
        ),
    ]
