# Generated by Django 4.2.7 on 2025-08-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse_monitor', '0003_rename_body_ticket_content_remove_ticket_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='ticket',
            name='recipient',
            field=models.CharField(default='tangentohost@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender',
            field=models.CharField(default='abuse@contabo.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
